### ISSUE TITLE
Linux hid_open_path not working

### ISSUE THREAD

**Issue by cyberjunky** [altera2015/ttwatcher#3]
Is the Linux version working when it comes to opening the hidraw device and reading files of it?
The currently used data to for m_Device in TTWatch::open() is

```
    this    @0x9c9f20   TTWatch
        [QObject]       QObject
        m_Counter   1 '\1'  quint8
        m_Device    0x0 hid_device *
        m_Path  "0005:0007:00"  QString
        m_Serial    "HE5045G00221"  QString
```

I doubt that you can use that path to open the device, but even if I specify the /dev/hidrawX it fails to get data..

Starting /home/ron/install/build-debug/src/ttwatcher...
DownloadDialog::workInfo "Loading Preferences" false 
TTWatch::downloadPreferences / failed to open. 
MainWindow::onWatchesChanged / unable to load preferences file. 
DownloadDialog::workInfo "Failed to load preferences" true 
DownloadDialog::workInfo "Done" true

**Comment by altera2015** [comment]
Just tested here and the latest branch with your fixes for pid/vid matching works on Linux. Just one small thing to do. Fix the permissions of the device:

```
$ cat /etc/udev/rules.d/99-tomtom.rules
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1390", ATTRS{idProduct}=="7474", MODE="666"
```

After this unplug and replug the watch and things should be rolling.

**Comment by cyberjunky** [comment]
I already had a similar udev rule for ttwatch.
Using latest code I still cannot fetch data from my watch.

[  891.140918] hid-generic 0003:1390:7474.0004: hiddev0,hidraw2: USB HID v1.01 Device [TomTom TomTom GPS Watch] on usb-0000:06:00.0-2.3.2.4/input0

$ ls -l /dev/hid*
crw------- 1 root root 249, 0 mei  7 19:46 /dev/hidraw0
crw------- 1 root root 249, 1 mei  7 19:46 /dev/hidraw1
crw-rw-rw- 1 root root 249, 2 mei  7 19:46 /dev/hidraw2

DownloadDialog::workInfo "Loading Preferences" false 
TTWatch::sendCommand / write failed. 
MainWindow::onWatchesChanged / unable to load preferences file. 
DownloadDialog::workInfo "Failed to load preferences" true 
DownloadDialog::workInfo "Done" true 

Sometimes the /dev/hidraw2 device disappears when trying to download.
The device gets found, but the very first hid command fails. 

Are all TT watches supported? I have a TT Runner Cardio with v1.8.35

**Comment by cyberjunky** [comment]
This code:

ttwatch.cpp:
bool TTWatch::sendCommand(const QByteArray &command, QByteArray &response)
{
...
   if ( hid_write( m_Device, data, 64) < 64 )
    {
        qDebug() << "TTWatch::sendCommand / write failed.";
        return false;
    }
...
}

**Comment by cyberjunky** [comment]
It's working now, it doesn't work if connected via a USB hub although there is enough power.

**Comment by altera2015** [comment]
I think this might have to do with the way hidlinux.c is resolving the device. It's using make_path

https://github.com/altera2015/ttwatcher/blob/master/src/hidlinux.c#L437

which tries to abstract the device path but looks like it's missing the hubs.

We can probably rewrite hid_open to work more like hid_enumerate and take make_path out of the equation.
