### ISSUE TITLE
Doesn't build anymore (on Ubuntu 14.04.3)

### ISSUE THREAD

**Issue by cyberjunky** [altera2015/ttwatcher#8]
../../src/SlippyMap.cpp: In member function ‘void SlippyMap::handleNetworkData(QNetworkReply_)’:
../../src/SlippyMap.cpp:306:40: error: no matching function for call to ‘SlippyMap::processTile(QPoint&, QByteArray)’
         processTile(tp, loadEmptyTile());
                                        ^
../../src/SlippyMap.cpp:306:40: note: candidate is:
../../src/SlippyMap.cpp:239:6: note: void SlippyMap::processTile(QPoint&, QByteArray&)
 void SlippyMap::processTile(QPoint &tp, QByteArray &data)
      ^
../../src/SlippyMap.cpp:239:6: note:   no known conversion for argument 2 from ‘QByteArray’ to ‘QByteArray&’
../../src/SlippyMap.cpp: In member function ‘bool SlippyMap::download(QPoint)’:
../../src/SlippyMap.cpp:350:42: error: no matching function for call to ‘SlippyMap::processTile(QPoint&, QByteArray)’
         processTile(grab, loadEmptyTile());
                                          ^
../../src/SlippyMap.cpp:350:42: note: candidate is:
../../src/SlippyMap.cpp:239:6: note: void SlippyMap::processTile(QPoint&, QByteArray&)
 void SlippyMap::processTile(QPoint &tp, QByteArray &data)
      ^
../../src/SlippyMap.cpp:239:6: note:   no known conversion for argument 2 from ‘QByteArray’ to ‘QByteArray&’
make[1]: *_\* [SlippyMap.o] Error 1
make[1]: Leaving directory `/home/ron/install/ttwatcher/build/src'
make: **\* [sub-src-ttwatcher-pro-make_first] Error 2

**Comment by altera2015** [comment]
Fixed build issues against Debian 8.2 ( Jessie ) and Qt 5.3. Hopefully that also takes care of Ubuntu.

https://github.com/altera2015/ttwatcher/commit/9bfac61f78bd9243f02c838bd90592e356d151b8

**Comment by cyberjunky** [comment]
That error is gone, but since you use QMarginsF now, it needs Qt 5.3, and Ubuntu 14.04.x is on 5.2.1

g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DQ_HTTP_STATIC_BUILD -DTT_RELEASE -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../src -I../../qhttpserver/src -I../../quazip/quazip -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I. -o bridge.o ../../src/bridge.cpp
../../src/bridge.cpp:4:21: fatal error: QMarginsF: No such file or directory
 #include <QMarginsF>
                     ^
compilation terminated.
make[1]: **\* [bridge.o] Error 1
make[1]: Leaving directory `/home/ron/install/ttwatcher/build/src'
make: **\* [sub-src-ttwatcher-pro-make_first] Error 2

ron@rdznl:~/install/ttwatcher/build$ qmake -v
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

**Comment by altera2015** [comment]
Removed dependency on QMarginsF

https://github.com/altera2015/ttwatcher/commit/270f3c9f3fe0b9343d94e60e29b35f9d57a908bc

**Comment by cyberjunky** [comment]
Thanks.

Next one; Not sure what issue is...:

../../src/bridgeeditordialog.cpp: At global scope:
../../src/bridgeeditordialog.cpp:305:6: warning: unused parameter ‘pos’ [-Wunused-parameter]
 void BridgeEditorDialog::bridgePointSelected(int index, QPoint pos)
      ^
../../src/bridgeeditordialog.cpp:311:6: warning: unused parameter ‘index’ [-Wunused-parameter]
 void BridgeEditorDialog::bridgePointUnselected(int index)
      ^
../../src/bridgeeditordialog.cpp: In member function ‘void BridgeEditorDialog::mapClicked(qreal, qreal)’:
../../src/bridgeeditordialog.cpp:339:12: warning: enumeration value ‘ER_NO_DATA’ not handled in switch [-Wswitch]
     switch ( m_Elevation.elevation(pos, elevation) )
            ^
../../src/bridgeeditordialog.cpp:339:12: warning: enumeration value ‘ER_SUCCESS’ not handled in switch [-Wswitch]
../../src/bridgeeditordialog.cpp: In member function ‘QString BridgeEditorDialog::baseDir() const’:
../../src/bridgeeditordialog.cpp:16:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: **\* [bridgeeditordialog.o] Error 1
make[1]: Leaving directory `/home/ron/install/ttwatcher/build/src'
make: **\* [sub-src-ttwatcher-pro-make_default] Error 2

**Comment by altera2015** [comment]
I think you missed the actual error. It looks like it was the AppDataLocation constant from Qt 5.4

Try https://github.com/altera2015/ttwatcher/commit/01adeab31e7615a28139a4cf3bd041f07775454d
